app/views/helpers/inputFile.scala.html
app/views/helpers/inputFileMulti.scala.html
app/views/helpers/inputRadioGroup.scala.html
app/views/helpers/inputText.scala.html

This probably needs review as I wasn't able to test the file upload fields, but input boxes and radio buttons seem to be working correctly.

Escape form fields correctly.

---

app/actions/AuthenticatedAction.scala
app/controllers/AppointAgentController.scala
app/controllers/agent/RepresentationController.scala
app/models/GroupAccount.scala
test/controllers/AppointAgentSpec.scala
test/resources/package.scala
test/utils/StubGroupAccountConnector.scala
test/utils/StubPropertyRepresentationConnector.scala

tests are not pending anymore
agentCode is not a Long, not a String

agent representation page

---

app/controllers/AddressLookup.scala
conf/messages
test/controllers/AddressLookupSpec.scala

This should close several related issues:
VTCCA-390
VTCCA-392
VTCCA-393
VTCCA-394

Remove space check on postcode lookup

---

app/config/ApplicationConfig.scala
app/controllers/ClaimProperty.scala
app/form/Mappings.scala
app/views/helpers/dateFields.scala.html
app/views/includes/errorSummary.scala.html
conf/application.conf
conf/messages
test/forms/CapacityDeclarationFormSpec.scala

Added validation for pre-1st April dates on property links
Added configurable 1st April threshold to allow testing
Fix missing day error messages on date inputs

Fixed error messages for date validations

---

app/views/helpers/dateFields.scala.html

VTCCA-507 Change invalid date field formats to say "Enter a valid date"

---

app/views/dashboard/manageProperties.scala.html
conf/messages

VTCCA-536 Adding a message to explain there is a delay

---

app/connectors/GroupAccounts.scala
app/connectors/IndividualAccounts.scala
app/controllers/CreateGroupAccount.scala
app/controllers/IdentityVerification.scala
app/models/GroupAccount.scala
app/models/GroupAccountSubmission.scala
app/models/IndividualAccount.scala
test/controllers/CreateGroupAccountSpec.scala
test/utils/StubIndividualAccountConnector.scala

This reverts commit 8136ef8503a1fdb7681b2f3889bef8e5045e224c.

Restore "Vtcca 697 (#203)"

---

app/controllers/agent/RepresentationController.scala
app/models/searchApi/AgentAuthResult.scala
app/models/searchApi/AgentAuthorisation.scala
app/views/dashboard/manageClientsSearchSort.scala.html
test/controllers/agent/ManageClientsSearchSortSpec.scala
test/resources/package.scala
test/utils/StubPropertyRepresentationConnector.scala

Use latest S&S API feature: representationStatus field and filter

VTCCA-768 fix client properties tab

---

conf/application.conf

rum-static.pingdom.net 
stats.g.doubleclick.net

Update security content policy

---

conf/application.conf

update content security policy

---

app/assets/css/searchAndSort.css
app/assets/javascripts/src/helper.js
app/views/dashboard/jsSearchSortPageSize.scala.html
app/views/dashboard/manageClientsSearchSort.scala.html
app/views/dashboard/managePropertiesSearchSort.scala.html

Non-JS version of new pagination layout

VTCCA-1085 search sort pagination non js

---

app/controllers/Assessments.scala
app/views/dvr/challenge_valuation.scala.html
app/views/dvr/requestDetailedValuation.scala.html
conf/app.routes
conf/messages
test/controllers/RequestDetailedValuationSpec.scala

Challenge DVR's displaying old screen

VTCCA-2226

---

app/connectors/CheckCaseConnector.scala
conf/application.conf

Check cases page failing if API throws Error

VTCCA-2261

---

app/views/dashboard/managedByAgentsProperties.scala.html
app/views/linkingRequestSubmitted.scala.html
app/views/propertyLinking/beforeYouStart.scala.html
app/views/propertyLinking/declaration.scala.html
app/views/propertyLinking/declareCapacity.scala.html
app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyLinking/uploadRatesBill.scala.html
app/views/propertyrepresentation/appoint/appointAgentSummary.scala.html
app/views/propertyrepresentation/revokeAgentSummary.scala.html

20 new IDs added to a variety of elements on the property linking pages

VTCCA-3040: adding IDs as requested to aid testing

---

app/assets/javascripts/src/fileUpload.js
app/views/propertyLinking/uploadRatesBill.scala.html

redirect user to sign in page when session expires on the upload rates bill page

VTCCA-3349: Redirect user to login if file upload initiate fails

---

app/assets/javascripts/src/fileUpload.js
app/controllers/IdentityVerification.scala
app/controllers/propertyLinking/UploadController.scala
app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyLinking/uploadRatesBill.scala.html

when user lost their session during property linking, redirect to sign in page, with a continue URL back to start of property linking journey

VTCCA-3349: change continueURL for linking

---

app/views/addUserToGG.scala.html

Agreed with Karen to remove problematic back button on this screen

CCAIA-878: remove back link

---

app/config/GuiceModule.scala
app/controllers/Assessments.scala
conf/application.conf
test/controllers/ViewAssessmentSpec.scala

This is required before I continue with the main part of this ticket (removing feature flags from VMV).

VTCCA-3421 remove flag

---

conf/app.routes

accidentally overwrote the previous fix!

VTCCA-3743 reapply the typo fix

---

app/views/govuk_wrapper.scala.html
app/views/includes/timeoutDialog.scala.html

Timeout Dialog should be shown only if user is logged in

VTCCA-3786 Property Linking Start page Timeout Dialog Bug

---

app/views/propertyrepresentation/manage/manageAgent.scala.html

Manage agents message key typo error

VTCCA-3824 Claim Property Type Error

---

app/actions/propertylinking/WithLinkingSession.scala
app/actions/propertylinking/requests/LinkingSessionRequest.scala
app/actions/requests/AuthenticatedRequest.scala
app/actions/requests/BasicAuthenticatedRequest.scala
app/controllers/propertyLinking/UploadController.scala
app/services/BusinessRatesAttachmentsService.scala
app/views/article.scala.html
app/views/linkingRequestSubmitted.scala.html
app/views/navigationBar.scala.html
app/views/propertyLinking/chooseEvidence.scala.html
app/views/propertyLinking/declaration.scala.html
app/views/propertyLinking/ownershipToProperty.scala.html
app/views/propertyLinking/relationshipToProperty.scala.html
app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyrepresentation/manage/manageAgent.scala.html
conf/messages
test/controllers/VoaPropertyLinkingSpec.scala
test/services/propertylinking/PropertyLinkingServiceSpec.scala

VTCCA-382 Bug fixing for Claim Property Journey

Vtcca 3824 bug fix

---

conf/messages

Signed-off-by: zahiriqbal <zahiriqbal@users.noreply.github.com>

Remove duplicate suffix from title

---

app/connectors/authorisation/BusinessRatesAuthorisationConnector.scala
test/controllers/detailedvaluationrequest/DvrControllerSpec.scala

…ness-rates-valuation-frontend

VTCCA-3987 Stop calling business-rates-authorisation getIDs 

---

app/controllers/Application.scala
app/controllers/agent/ManageAgentController.scala
app/controllers/agent/RepresentationController.scala
app/controllers/agentAppointment/AddAgentController.scala
app/controllers/propertyLinking/ClaimPropertyRelationshipController.scala
app/views/mainLayout.scala.html
app/views/propertyLinking/beforeYouStart.scala.html
test/controllers/agent/ManageAgentControllerSpec.scala
test/controllers/propertyLinking/ClaimPropertyRelationshipControllerSpec.scala

also, updated "Page" to "View" for consistency throughout the project

VTCCA-4046: migrated beforeYouStart page

---

app/controllers/Application.scala
app/controllers/Register.scala
app/views/dashboard/assessmentDetails.scala.html
app/views/dashboard/assessments.scala.html
app/views/mainLayout.scala.html
app/views/start.scala.html
test/controllers/ApplicationSpec.scala
test/controllers/RegisterPageSpec.scala
test/uk/gov/hmrc/propertylinking/controllers/valuations/ValuationsControllerSpec.scala
test/utils/DesignSystemTestSupport.scala

gds migration for start page
bug fixed for vtcca 4045 for assessment page

VTCCA-4056: gds migration start page

---

app/controllers/detailedvaluationrequest/DvrController.scala

Use explicit format string consistently across services

VTCCA-4192 date formatter

---

app/views/propertyrepresentation/appoint/appointAgentProperties.scala.html
test/controllers/agentAppointment/AppointAgentControllerSpec.scala
test/utils/FakeObjects.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4395

VTCCA-4395 dropdown not remembering selected agent fix

---

app/config/ApplicationConfig.scala
conf/application.conf

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4540

VTCCA-4540 - Added in feature flag for new registration journey

---

app/views/dvr/cannotRaiseChallenge.scala.html
app/views/includes/assessmentHeading.scala.html
app/views/linkingRequestSubmitted.scala.html
app/views/propertyLinking/declaration.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4506

VTCCA-4506 extracted header to new file

---

README.md
app/assets/css/searchAndSort.css
app/assets/stylesheets/_sortable.scss
app/assets/stylesheets/application.scss
app/views/includes/designSystemsStylesheets.scala.html
app/views/propertyrepresentation/appoint/appointAgentProperties.scala.html
app/views/propertyrepresentation/revokeAgentProperties.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4509

VTCCA-4509 Update Appoint an agent to one or more properties sortable table columns with accessible component

---

app/assets/stylesheets/application.scss
app/controllers/Assessments.scala
app/views/dvr/challengeCasesDetails.scala.html
app/views/dvr/checkCasesDetails.scala.html
app/views/dvr/dvrFiles.scala.html
conf/messages
test/controllers/detailedvaluationrequest/DvrControllerSpec.scala
test/utils/FakeViews.scala
test/utils/GdsComponents.scala
test/utils/HtmlPage.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4545

VTCCA-4545 reformatted DVR page

---

conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4607

VTCCA-4607 get help link message updated

---

app/views/dvr/dvrFiles.scala.html
test/controllers/detailedvaluationrequest/DvrControllerSpec.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4619

VTCCA-4619 fixed DVR Valuation link

---

app/views/linkingRequestSubmitted.scala.html
conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4406

VTCCA-4066: Updated page title

---

conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4653

VTCCA-4653 fix messages on new registration page

---

app/controllers/detailedvaluationrequest/DvrController.scala
app/models/dvr/PropertyLinkForDvr.scala
app/views/dvr/requestedDetailedValuation.scala.html
app/views/includes/assessmentHeading.scala.html
conf/messages
test/controllers/detailedvaluationrequest/DvrControllerSpec.scala
test/utils/FakeObjects.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4593

VTCCA-4593 update request a dvr confirmation page

---

app/controllers/propertyLinking/ChooseEvidenceController.scala
app/views/propertyLinking/chooseEvidence.scala.html
conf/messages
test/controllers/propertyLinking/ChooseEvidenceControllerSpec.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4635

VTCCA-4635 copy of the br bills view updated

---

app/controllers/propertyLinking/UploadController.scala
app/views/propertyLinking/uploadRatesBill.scala.html
conf/messages
test/controllers/propertyLinking/FileUploadControllerSpec.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4637

VTCCA-4637 upload rates bill layout updated

---

app/views/propertyLinking/relationshipToProperty.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4617

VTCCA-4617 loose ends

---

app/views/dashboard/assessmentDetails.scala.html
conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4720

VTCCA-4720 added aria-lable

---

app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyrepresentation/manage/manageAgentProperties.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4714

VTCCA-4714 change heading sizes

---

app/views/propertyLinking/uploadRatesBill.scala.html
conf/messages

Ticket: https://jira.tools.tax.service.gov.uk/browse/VTCCA-4637. This is a fix of a warning message, all the rest of acceptance criteria has been fulfilled here:  https://github.com/hmrc/voa-property-linking-frontend/pull/1063

VTCCA-4637 warning text for agent added

---

app/views/propertyrepresentation/manage/myAgents.scala.html
conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4709

VTCCA-4709 added aria lable to the link

---

app/views/includes/assessmentHeading.scala.html
app/views/propertyrepresentation/appoint/appointAgentProperties.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4712

VTCCA-4712 remove duplicate ids

---

app/views/propertyrepresentation/manage/manageAgentProperties.scala.html
app/views/propertyrepresentation/manage/myAgents.scala.html
conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4713
Minor screen change agreed between Karen and Zahir (add Action table header)

VTCCA-4713 remove empty cells

---

app/views/propertyLinking/declaration.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4622

VTCCA-4622 Test Summary link fixed

---

app/views/dvr/checkCasesDetails.scala.html

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4758

VTCCA-4758 fix broken empty checks tab on dvr screen

---

app/controllers/propertyLinking/DeclarationController.scala
app/views/propertyLinking/declaration.scala.html
test/controllers/propertyLinking/DeclarationControllerSpec.scala
test/utils/FakeViews.scala
test/utils/HtmlPage.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4736

VTCCA-4736 Check your answers - Wales

---

app/assets/javascripts/src/application.js
app/assets/javascripts/src/fileUpload.js
app/assets/javascripts/src/updateEvidenceType.js
app/assets/javascripts/src/updateOtherEvidencePage.js
app/controllers/propertyLinking/UploadController.scala
app/models/EvidenceType.scala
app/models/FileInfo.scala
app/models/attachment/request/InitiateAttachmentRequest.scala
app/services/BusinessRatesAttachmentsService.scala
app/views/propertyLinking/cannotProvideEvidence.scala.html
app/views/propertyLinking/declaration.scala.html
app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyLinking/uploadRatesBill.scala.html
conf/app.routes
conf/messages
test/connectors/BusinessRatesAttachmentsConnectorSpec.scala
test/controllers/propertyLinking/FileUploadControllerSpec.scala
test/services/BusinessRatesAttachmentsServiceSpec.scala
test/utils/FakeObjects.scala
test/utils/FakeViews.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4641

VTCCA-4641 other evidence page

---

app/views/propertyrepresentation/manage/myAgents.scala.html
conf/messages
test/controllers/agent/ManageAgentControllerSpec.scala
test/utils/FakeViews.scala

note, I didn't post a JIRA link

VTCCA-4785 add new link to Appoint an agent to Manage Agents

---

app/controllers/Assessments.scala
app/models/PropertyLink.scala
app/uk/gov/hmrc/propertylinking/controllers/valuations/ValuationsController.scala
app/views/dashboard/assessmentDetails.scala.html
app/views/dashboard/assessments.scala.html
test/uk/gov/hmrc/propertylinking/controllers/valuations/ValuationsControllerSpec.scala
test/utils/FakeObjects.scala

VIEW_DETAILED_VALUATION allowedAction needs to be present in order for a
detailed valuation link to be displayd

VTCCA-4784 don't display valuations if you can't click them

---

conf/application.conf

As the flag is set to true in QA in app-config, we should also set to true in local

VTCCA-0 set newRegistrationJourneyEnabled to true

---

app/utils/FrontendComponentHelper.scala
app/views/createAccount/registerAssistantAdmin.scala.html
app/views/createAccount/registerIndividual.scala.html
app/views/createAccount/registerOrganisation.scala.html
app/views/helpers/dateFields.scala.html
test/controllers/RegistrationControllerSpec.scala
test/utils/FakeViews.scala
test/utils/FrontendComponentHelperSpec.scala

https://jira.tools.tax.service.gov.uk/browse/VTCCA-4416

VTCCA-4416 Date validation improvements

---

app/assets/javascripts/src/updateOtherEvidencePage.js
app/controllers/propertyLinking/UploadController.scala
app/views/propertyLinking/uploadEvidence.scala.html
app/views/propertyLinking/uploadRatesBill.scala.html
conf/application-json-logger.xml
conf/logback.xml
conf/messages

text changes
error summary agreed fix
started to address the misuse of `class="govuk-visually-hidden"`

VTCCA_4907 error message bugfix

---

app/controllers/propertyLinking/ClaimPropertyRelationshipController.scala
app/models/LinkingSession.scala
conf/app.routes
test/controllers/propertyLinking/ClaimPropertyOccupancyControllerSpec.scala
test/controllers/propertyLinking/ClaimPropertyRelationshipControllerSpec.scala
test/utils/FakeViews.scala

claim property backlink fix for other valuations

VTCCA-5012 bugfix

---

app/controllers/propertyLinking/ChooseEvidenceController.scala
app/controllers/propertyLinking/ClaimPropertyRelationshipController.scala

VTCCA-5012 Welsh and English future valuations fixed

---

conf/messages

https://jira.tools.tax.service.gov.uk/browse/VTCCA-5040

VTCCA-5040 amended the instruction

---

conf/messages.cy
it/controllers/registration/RegistrationConfirmationISpec.scala

Update terms and conditions link for Welsh 'new' registration success page

VTCCA-5979

---

app/views/dvr/dvrFiles.scala.html
app/views/dvr/tabs/checkCasesDetailsTab.scala.html
app/views/dvr/tabs/valuationTab.scala.html
app/views/includes/analytics.scala.html
app/views/includes/scripts.scala.html
app/views/manageAgent/areYouSure.scala.html
app/views/propertyLinking/declaration.scala.html
app/views/propertyrepresentation/revokedAgentPrivileges.scala.html
build.sbt
conf/application.conf
project/plugins.sbt

updated bootstrap for CSP
acceptance tests pass, copy of logs included

VTCCA-6248 update bootstrap to include new CSP filter
